CREATE DATABASE PORTAL;

USE PORTAL;

CREATE TABLE ICON (
	CD_ICON INT AUTO_INCREMENT,
	NM_ICON VARCHAR(50) NOT NULL,
	LC_ICON VARCHAR(255) NOT NULL,
	IMG_ICON VARCHAR(30) NOT NULL,
	TP_ICON INT NOT NULL,
    TP_TARGET CHAR(10),
	PRIMARY KEY (CD_ICON)
);

CREATE TABLE TEXT (
	CD_TEXT INT AUTO_INCREMENT,
    TP_TEXT ENUM('T','D'),
    DS_TEXT VARCHAR(500),
    PRIMARY KEY (CD_TEXT)
);

CREATE TABLE RAMAIS (
	ID_RAMAL INT AUTO_INCREMENT,
	CD_RAMAL INT(4) NOT NULL,
    DS_SETOR VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_RAMAL)
);
